//! `issen-parsers` — internal aggregator umbrella (NOT a parser itself).
//!
//! Force-links every `issen-parser-*` crate listed in this crate's own
//! `Cargo.toml` `[dependencies]`, so each parser's `inventory::submit!`
//! registration survives dead-code elimination in any artifact that links
//! `issen_cli`. The anchors are generated by `build.rs` from the manifest — there
//! are zero hand-written `extern crate` lines. Adding a parser is one dependency
//! line in `Cargo.toml`.
//!
//! `issen_cli`'s `lib.rs` carries a real `extern crate issen_parsers as _;` root
//! anchor so this crate (and therefore the whole generated anchor set) is itself
//! pulled into the link.
#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]

include!(concat!(env!("OUT_DIR"), "/anchors.rs"));

#[cfg(test)]
mod drift_gate {
    //! Anchor-completeness gate: every direct normal dependency declared in this
    //! crate's own `Cargo.toml` MUST appear as a real `extern crate <dep> as _;`
    //! in the generated `anchors.rs`. If build.rs ever silently drops a dep (or a
    //! dep is added without regenerating), this fails — a dropped anchor means the
    //! parser's `inventory::submit!` is dead-code-eliminated and it never runs.
    //!
    //! Both inputs are read from THIS crate's build (manifest dir + `OUT_DIR`), so
    //! the gate never hunts the target directory and never goes stale.

    const ANCHORS_RS: &str = include_str!(concat!(env!("OUT_DIR"), "/anchors.rs"));
    const MANIFEST: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/Cargo.toml"));

    /// Direct normal deps declared under `[dependencies]` in this crate's manifest.
    fn manifest_deps() -> Vec<String> {
        let manifest: toml::Value = MANIFEST.parse().expect("aggregator Cargo.toml parses");
        manifest
            .get("dependencies")
            .and_then(toml::Value::as_table)
            .map(|t| t.keys().cloned().collect())
            .unwrap_or_default()
    }

    #[test]
    fn every_manifest_dep_is_anchored() {
        let missing: Vec<String> = manifest_deps()
            .into_iter()
            .filter(|dep| {
                let line = format!("extern crate {} as _;", dep.replace('-', "_"));
                !ANCHORS_RS.contains(&line)
            })
            .collect();
        assert!(
            missing.is_empty(),
            "these manifest deps are NOT anchored in the generated anchors.rs — \
             their inventory registrations will be dead-code-eliminated and the \
             parser will silently never run: {missing:?}"
        );
    }

    #[test]
    fn no_extra_anchors_beyond_manifest() {
        // The generated set must be EXACTLY the manifest deps — a stray anchor for
        // a crate not in `[dependencies]` would not compile, but guard against a
        // future build.rs that pulls extra (e.g. transitive) names.
        let deps: std::collections::HashSet<String> = manifest_deps()
            .into_iter()
            .map(|d| d.replace('-', "_"))
            .collect();
        for line in ANCHORS_RS.lines() {
            let line = line.trim();
            if let Some(rest) = line.strip_prefix("extern crate ") {
                let ident = rest
                    .strip_suffix(" as _;")
                    .expect("anchor line ends with ` as _;`");
                assert!(
                    deps.contains(ident),
                    "generated anchor `{ident}` has no matching [dependencies] entry"
                );
            }
        }
    }
}
