//! Generate one real `extern crate <dep> as _;` link anchor per direct normal
//! dependency declared in THIS crate's own `Cargo.toml`.
//!
//! The aggregator's `[dependencies]` table is the single source of truth for the
//! parser anchor set; this script reads that manifest (NOT `cargo_metadata` —
//! the resolved graph would pull in transitive crates we must not anchor) and
//! emits `OUT_DIR/anchors.rs`, which `src/lib.rs` `include!`s. Adding a parser is
//! one dependency line here; the build regenerates the anchor.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let manifest_path = Path::new(&manifest_dir).join("Cargo.toml");
    println!("cargo:rerun-if-changed=Cargo.toml");

    let manifest_text = fs::read_to_string(&manifest_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", manifest_path.display()));
    let manifest: toml::Value = manifest_text
        .parse()
        .unwrap_or_else(|e| panic!("parse {}: {e}", manifest_path.display()));

    // Direct, normal deps only — never [build-dependencies] / [dev-dependencies]
    // (toml's own build-dep would otherwise be anchored into the crate graph).
    let mut deps: Vec<String> = manifest
        .get("dependencies")
        .and_then(toml::Value::as_table)
        .map(|t| t.keys().cloned().collect())
        .unwrap_or_default();
    deps.sort();

    let mut out =
        String::from("// @generated by build.rs from Cargo.toml [dependencies] — DO NOT EDIT.\n");
    for dep in &deps {
        // Crate names use `-`; the Rust path identifier uses `_`.
        let ident = dep.replace('-', "_");
        out.push_str(&format!("extern crate {ident} as _;\n"));
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let anchors_path = Path::new(&out_dir).join("anchors.rs");
    fs::write(&anchors_path, out)
        .unwrap_or_else(|e| panic!("write {}: {e}", anchors_path.display()));

    // Also emit a plain manifest of the anchored crate names so a drift gate can
    // read the expected set without re-parsing Cargo.toml itself.
    let manifest_list_path = Path::new(&out_dir).join("anchored_crates.txt");
    fs::write(&manifest_list_path, deps.join("\n"))
        .unwrap_or_else(|e| panic!("write {}: {e}", manifest_list_path.display()));
}
