//! `issen-providers` — internal aggregator umbrella (NOT a provider itself).
//!
//! Force-links every container/provider crate listed in this crate's own
//! `Cargo.toml` `[dependencies]`, so each provider's inventory registration
//! survives dead-code elimination in any artifact that links `issen_cli`. The
//! anchors are generated by `build.rs` from the manifest — zero hand-written
//! `extern crate` lines. Adding a provider is one dependency line in `Cargo.toml`.
//!
//! `issen_cli`'s `lib.rs` carries a real `extern crate issen_providers as _;`
//! root anchor so this crate is itself pulled into the link.
#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]

include!(concat!(env!("OUT_DIR"), "/anchors.rs"));

#[cfg(test)]
mod drift_gate {
    //! Anchor-completeness gate: every direct normal dependency declared in this
    //! crate's own `Cargo.toml` MUST appear as a real `extern crate <dep> as _;`
    //! in the generated `anchors.rs`. A dropped anchor means the provider's
    //! inventory registration is dead-code-eliminated and it never runs.

    const ANCHORS_RS: &str = include_str!(concat!(env!("OUT_DIR"), "/anchors.rs"));
    const MANIFEST: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/Cargo.toml"));

    fn manifest_deps() -> Vec<String> {
        let manifest: toml::Value = MANIFEST.parse().expect("aggregator Cargo.toml parses");
        manifest
            .get("dependencies")
            .and_then(toml::Value::as_table)
            .map(|t| t.keys().cloned().collect())
            .unwrap_or_default()
    }

    #[test]
    fn every_manifest_dep_is_anchored() {
        let missing: Vec<String> = manifest_deps()
            .into_iter()
            .filter(|dep| {
                let line = format!("extern crate {} as _;", dep.replace('-', "_"));
                !ANCHORS_RS.contains(&line)
            })
            .collect();
        assert!(
            missing.is_empty(),
            "these manifest deps are NOT anchored in the generated anchors.rs — \
             their inventory registrations will be dead-code-eliminated: {missing:?}"
        );
    }

    #[test]
    fn no_extra_anchors_beyond_manifest() {
        let deps: std::collections::HashSet<String> = manifest_deps()
            .into_iter()
            .map(|d| d.replace('-', "_"))
            .collect();
        for line in ANCHORS_RS.lines() {
            let line = line.trim();
            if let Some(rest) = line.strip_prefix("extern crate ") {
                let ident = rest
                    .strip_suffix(" as _;")
                    .expect("anchor line ends with ` as _;`");
                assert!(
                    deps.contains(ident),
                    "generated anchor `{ident}` has no matching [dependencies] entry"
                );
            }
        }
    }
}
